spring.application.name=delivery

spring.datasource.url=jdbc:mysql://localhost:3306/delivery?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.config.import=optional:file:./config/application-secret.properties

jwt.secret=vV9XbS2zG3dK8yA6fR5wN1pE0mT4hL7cQ2jB4xU8nF1oI5eZ9rA3uM7kC6vD1bY2
jwt.expiration=3600000